# Generated by Django 3.2.20 on 2023-08-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../default_image_v7fh2u', upload_to='images/'),
        ),
    ]
